[package]
name = "qlib-rs-derive"
version = "0.1.0"
edition = "2021"
description = "Derive macros for qlib-rs RESP protocol"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0", features = ["full"] }
quote = "1.0"
proc-macro2 = "1.0"